### ISSUE TITLE
$.param.fragment: "Uncaught TypeError: Cannot read property '3' of null"

### ISSUE THREAD

**Issue by carbocation** [cowboy/jquery-bbq#15]
I'm using BBQ 1.3-min - it seems pretty awesome. However, I cannot get the critical $.param.fragment() function to work. When I try even a canonical example from the documentation, such as:
var newUrl = $.param.fragment( "index.php", "/path/to/file.php", 2 );

I get the following error in Chrome for that line:
Uncaught TypeError: Cannot read property '3' of null

Removing the final parameter (2) has no effect.

Any chance this is not on my end?

**Comment by cowboy** [comment]
First, jQuery BBQ 1.3 hasn't been released yet, it's in an alpha state. If you need a production version, I'd recommend using version 1.2.

That being said, I just tried doing `var newUrl = $.param.fragment( "index.php", "/path/to/file.php", 2 )` in the console on [this example page](http://benalman.com/code/projects/jquery-bbq-dev/examples/deparam/), which uses jQuery BBQ 1.3pre dated 8/20, and don't get any errors.

Can you post a live example of this somewhere so I can see the error?

**Comment by carbocation** [comment]
Wait, using alpha code on a live site isn't best practice? Kidding - I somehow failed to see that, but you clearly labeled it - my fault!

This sounds like it's a problem in my code, not yours. If the bug persists after I clean up my code, I'll post a live link. Thanks for your quick reply.

**Comment by carbocation** [comment]
It was an error on my end; thanks for taking a look, though.
