### ISSUE TITLE
jQuery hashchange - Safari 4 - Hash change event throws error after navigating to a page on a different domain

### ISSUE THREAD

**Issue by csytan** [cowboy/jquery-bbq#2]
To reproduce (in Safari 4, OSX):
1. Visit http://benalman.com/code/projects/jquery-hashchange/examples/hashchange/
2. Click on the Test buttons to trigger hash change
3. Visit  http://google.com (or another domain)
4. Click the back button several times.  The first hash change will throw an error.

The error returned is:
    TypeError: Result of expression 'url' [undefined] is not an object.
    Line 91 on: jquery.ba-hashchange.js

Cheers & Thanks for the great plugin

**Comment by csytan** [comment]
Moved issue to the correct project

**Comment by cowboy** [comment]
I've filed a webkit bug report on this, and set up an example page:
http://benalman.com/code/projects/jquery-hashchange/examples/bug-safari-back-from-diff-domain/

**Comment by cowboy** [comment]
I've also come up with a fix—can you tell me if this version works?
http://benalman.com/code/projects/jquery-hashchange/jquery.ba-hashchange.js

**Comment by csytan** [comment]
Tested.  The new version works great.  Thanks!

**Comment by jacobwod** [comment]
Thank you for working on this issue. I'm experiencing it too, with the larger BBQ Library. I tried using the code you supplied here (the 1.1.1 version) and changed that part of jquery.bbq (below line 815), to use this new code. But it seems like this get_fragment() is defined twice, and even though the new version (line 906) would work, I still get this very same error, now on line 124. I compared the differences you made between 1.1 and this bug fix, and there seem to be more than just a one-liner. Is there any chance you could try solving this in the jquery.bbq.js as well? Thank you!

**Comment by cowboy** [comment]
Yes, now that I know how to apply the fix, I'll have to do the same to BBQ separately. I'm going to release both as soon as I get the chance, but it may be later this week before I can work on it.

**Comment by jacobwod** [comment]
Thanks for the update in jquery-haschange (1.2) you commited last weekend!
Unfortunately, it still looks like the update requires some changes in jquery-bbq in order to work as well. If you need any help debugging, I'd be happy to try it out in a rather complex project.

**Comment by jacobwod** [comment]
Hi Ben! I tried the latest release of BBQ (1.2) on Jquery 1.4.2. The following occurs on Safari (4.0.3) after navigating to a page outside my domain and returning (using back-button).

These errors are thrown when I call functions that are meant to update the hash string by using $.bbq.pushState() function:

Line 131: TypeError: undefined is not an object
Line 268: TypeError: Result of expression 'is_string' [undefined] is not an object.

All other browsers work fine (including FF 3.5.7 & 3.6, Opera 10.10 & 10.5, Chrome 2, WebKit (nighly build, all on Mac) and IE6(!) IE7 and IE8).

**Comment by cowboy** [comment]
Oops, my bad! This should be all fixed now in 1.2.1:
http://github.com/cowboy/jquery-bbq/tree/v1.2.1

**Comment by jacobwod** [comment]
Excellent, it looks to me as you just got rid of this issue. Thank you!

**Comment by cowboy** [comment]
Great, closing the issue.
