### ISSUE TITLE
malformed URI sequence

### ISSUE THREAD

**Issue by adoerler** [cowboy/jquery-bbq#21]
Hello everybody,

i have a little problem with this nice plugin.

The registered trademark sign "®" is url encoded "%AE" (escape("®") = "%AE").

If there is a "%AE" in the url, jQuery-BBQ throws an error: "malformed URI sequence".
Try this for example: $.deparam.querystring('http://example.com/?testRegisteredTradeMark=%AE');

It is not the "%" sign in general, as something like this works without problems:

$.deparam.querystring('http://example.com/?testRegisteredTradeMark=blank%20space');

Does anyone has an idea how to fix this issue?

Thank you very much in advance
Andreas

**Comment by cowboy** [comment]
Andreas, "®" is properly url-encoded as "%C2%AE". You should be using `encodeURIComponent` (or the server-side equivalent) instead of `escape`. Note that jQuery's own `$.param` method uses `encodeURIComponent` while BBQ's `$.deparam` method(s) use `decodeURIComponent` internally.

See the [MDC warning for escape/unescape](https://developer.mozilla.org/en/Core_JavaScript_1.5_Guide/Functions#escape_and_unescape_Functions) for more information.

```
encodeURIComponent("®") // "%C2%AE"
decodeURIComponent("%C2%AE") // "®"

escape("®") // "%AE"
decodeURIComponent("%AE") // URIError: URI malformed
```

**Comment by adoerler** [comment]
Hello cowboy,

thank you for your fast response.

If I request the following url in Firefox http://www.google.at/search?num=100&hl=de&safe=off&q=test®, it turns into http://www.google.at/search?num=100&hl=de&safe=off&q=test%AE. 

I've also tried with Live HTTP headers. The request shows up with %AE and not %C2%AE.

The same thing happens if I send ® in a form with a GET request. So it seems that the browser itself converts it to %AE. 

I'll try to encode the url correctly (%C2%AE) and redirect the user to the correct url. Thisi way jquery-bbq should work. Thank you for the suggestion.

Greetings from Austria
Andreas

**Comment by cowboy** [comment]
In Firefox 3.6 and 4.0 with both JavaScript enabled and disabled, If I go to google and type `test®` into the search box then press enter, the address bar shows `q=test®` but when it is copied into the clipboard, it shows as `q=test%C2%AE`.

At this point, if I examine `decodeURIComponent(location.hash)` (JS enabled) or `decodeURIComponent(location.search)` (JS disabled), I see `q=test®`.

I get these same results in Chrome as well (even though the address bar shows `q=test%C2%AE` in Chrome when JS is enabled).

I haven't been able to test in Internet Explorer, but are you sure this is what's happening in Firefox?

**Comment by adoerler** [comment]
Hello again,

I've found my problem. You were absolutly right in your first comment. Using encodeURIComponent is the way to go.
I had a submit event bound to my search form which still used the encode()-function. 
After replacing it and removing the now unneded utf8_encode of the request parameter everything is working now.

Thank's for your help!
Andreas
