### ISSUE TITLE
Support location.replace in pushState

### ISSUE THREAD

**Issue by darkman666** [cowboy/jquery-bbq#23]
It will be good if pushState can use location.replace for chage state. It may be vary helpful on app initialization. When user open short form of url, app automaticaly set default state in hash with replace current url in history, so even first state wil work with back/next right.

So jq_bbq.pushState will look something like:
jq_bbq.pushState = jq_bbq_pushState = function (params, merge_mode, useReplace) {
        if (is_string(params) && /^#/.test(params) && merge_mode === undefined) {
            // Params string begins with # and merge_mode not specified, so completely
            // overwrite window.location.hash.
            merge_mode = 2;
        }

```
    var has_args = params !== undefined,
    // Merge params into window.location using $.param.fragment.
  url = jq_param_fragment(location.href,
    has_args ? params : {}, has_args ? merge_mode : 2);

    // Set new window.location.href. Note that Safari 3 & Chrome barf on
    // location.hash = '#' so the entire URL is set.
    if (!useReplace || !location.replace) {
        location.href = url;
    }
    else {
        location.replace(url);
    }
};
```

**Comment by cowboy** [comment]
This is actually something I'm working on adding into my [jQuery hashchange event](http://github.com/cowboy/jquery-hashchange) plugin, but until I can get it to work reliably cross-browser, I won't add it.

That being said, if I can get it to work, I will add a new method called `replaceState()`.

**Comment by earshinov** [comment]
Is there any progress on this issue? What are the cross browser problems you mention?

**Comment by cnelson** [comment]
I'm also interesting in this functionality.  Would be curious to know what cross browser issues you've seen as well.  Might help those who want to contribute a fix towards this to make sure they are addressing known problems when doing so.

**Comment by krisselden** [comment]
Does not work in Safari until very recent versions, and does not work in Mobile Safari iOS version 5.0 or less. Replace will update the url and not create a new history entry, fire the hashchange event, but it doesn't actually replace the history entry. So when you add another history entry, then click back, you go back to the original entry not the replaced entry.

**Comment by jayaddison** [comment]
Closing some old issues; this one's unlikely to be addressed since [`History.replaceState`](https://developer.mozilla.org/en-US/docs/Web/API/History/replaceState) is available in HTML5 and is probably worth looking into during relevant migration / upgrades.
