### ISSUE TITLE
How to make it work in IE6/IE7/IE8-compat

### ISSUE THREAD

**Issue by Shinta** [cowboy/jquery-bbq#27]
Hello, I read all the docs, tons of issues I can't make my script to work, IE keep throwing me "Access is denied" error.
Using: 
- jQuery BBQ: Back Button & Query Library - v1.2.1 - 2/17/2010
- jQuery hashchange event - v1.2 - 2/11/2010

Is there something I need to set, or change?

Thanks in advanced.

**Comment by cowboy** [comment]
Can you try the latest 1.3pre pre-release version of jQuery BBQ on GitHub?

**Comment by Shinta** [comment]
Thanks for your response.

I tested it with the 1.3pre and throws me an error in line 1348 - Access is denied, using IE8 compat mode, with jQuery1.4.4
Can the subdomain be a problem?, because the web is part of a network, sub.maindomain.com. I saying this because locally works like a charm.

**Comment by Shinta** [comment]
Fixed!

**Comment by cowboy** [comment]
Ok, great.. closing the issue!

**Comment by stevemulligan** [comment]
Can I ask what the solution was?  I get the same error on line 1348 with 1.3pre in IE
