### ISSUE TITLE
IE8 converts certain parameters to HTML entities

### ISSUE THREAD

**Issue by RomanShumikhin** [cowboy/jquery-bbq#30]
I have this url

http://localhost:8080/dev/me.html#l=dynlists

In my code I push the state like this:

$.bbq.pushState({"copy": "dl-123456789});

Which produces an url like this

http://localhost:8080/dev/me.html#l=dynlists&copy=dl-123456789

IE8 interprets "&copy" part as HTML entity © (copyright sign), this results in the following url in IE8, which is obviously wrong.

http://localhost:8080/dev/me.html#l=dynlists&©=dl-123456789

I am using jQuery BBQ Version: 1.2.1

I haven't checked it in other versions of IE, they might have similar problem.

**Comment by cowboy** [comment]
This is a known issue with IE and can't easily be worked around. I don't know of a solution, to be honest. My advice would be to not use keynames that are also HTML entities.

**Comment by RomanShumikhin** [comment]
Ben,

I see... Thank you so much for responding so quickly. It really helped me :-)

Roman
