### ISSUE TITLE
malformed URI sequence (again)

### ISSUE THREAD

**Issue by ejn** [cowboy/jquery-bbq#33]
I'm having a problem with parsing the query string using $.deparam.querystring(window.location.search) under Firefox 7.0.1. I type the query string in the address bar (?problem=ä) and hit enter, and it changes any umlauts into the "escape"-d version (so ä becomes %E4 and not %C3%A4. I then try parsing the querystring and get, logically enough, a malformed URI sequence (at line 406 in jquery.ba-bbq.js v1.2.1 to be precise).

My quick hack which seems to be doing the trick for me (tested in FF and IE) is to instead of just having decode as an alias of decodeURIComponent then to have it (in line 86 of jquery.ba-bbq.js v1.2.1) as 

```
decode function (string) {
    try {
        return decodeURIComponent(string);
    } catch(e) {
        return unescape(string);
    }
};
```

This way we first try to do the proper thing, and then resort to cheap hacks if it didn't work properly.

Apart from being a bit quick'n'dirty, is there any reason not to do this?

**Comment by jayaddison** [comment]
Closing as part of a clean-up of old issues.  FWIW, a decade later, `unescape` is considered legacy/undesirable according to [ECMA-262 Annex B](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-additional-ecmascript-features-for-web-browsers).
