### ISSUE TITLE
Allow pushState to accept data in the form $.bbq.pushState(key, value)

### ISSUE THREAD

**Issue by csnover** [cowboy/jquery-bbq#4]
Currently only an object or serialized string is accepted. Sad :(

**Comment by jayaddison** [comment]
Closing as part of a review of old issues.  FWIW, serializing data to/from string may be possible in many cases - and given that it's now 2020 the HTML5 [`History.pushState`](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState) method's probably the route to take.
