### ISSUE TITLE
Get into bower!

### ISSUE THREAD

**Issue by atrauzzi** [cowboy/jquery-bbq#45]
Would love it if I could add you to my dependencies list and manage source checkouts from there! :)

**Comment by benjaminreid** [comment]
2nd this.

**Comment by raffazizzi** [comment]
yes please.

**Comment by drywall** [comment]
Thirdsies.

**Comment by MetaMemoryT** [comment]
fourth

**Comment by arippberger** [comment]
+1

**Comment by mvastola** [comment]
+1

**Comment by mvastola** [comment]
Just a gentle ping @cowboy to follow-up on this..

**Comment by ghost** [comment]
yes.

**Comment by StarveTheEgo** [comment]
Rip

**Comment by jayaddison** [comment]
Closing some old issues.  `bower` looks like it's in maintenance-only mode currently, but either way, `jquery-bbq`'s available there in packaged form.
