### ISSUE TITLE
BBQ dead?

### ISSUE THREAD

**Issue by SamMousa** [cowboy/jquery-bbq#49]
Is jquery-bbq dead?

@cowboy If you are no longer maintaining it but wouldn't mind someone else taking over, please let us know so we at least know what to do!

Cheers and thnx for the great plugin =)

**Comment by cowboy** [comment]
I could actually use help maintaining this and jquery-hashchange, but before I do anything I need to figure out a few things:
- refactoring of inline docs to separate files (markdown?)
- automate Grunt-based build / publish process and multi-browser testing

**Comment by SamMousa** [comment]
I don't have a lot of time, but at least anyone checking up on the project will be able to offer =)

Do you have some time to merge one of the pull request fixing the current compatibility bug? Because afaik that is the only real bug at the moment!

**Comment by galimk** [comment]
that would be great if you can merge that fix from the pull request :+1: Was actually looking at bbq yesterday and considered using History.js because if this bug, but BBQ fits my model better.

**Comment by yscumc** [comment]
Agreed, would be great if someone can at least update it to support the newest jQuery versions

**Comment by noslouch** [comment]
I guess there's always the jQuery migrate plugin for the meantime: https://github.com/jquery/jquery-migrate/

**Comment by justgage** [comment]
Yeah this is sad, I can't seem to find any plugin that is really well supported.

**Comment by sytelus** [comment]
Looks like several pull requests are piling up to fix .browser issue. Any chance to accept any one of them so at least we can get out of broken state? I'd really hate to use migrate plugin...

**Comment by WilliamStam** [comment]
sorry to re open an ancient thread.. but it really would be nice if you could merge one of the browser pull request fixes in. using composer to manage my dependencies.. dont want to have to add a manual file into my project with the fix.. but thats what im needing to do cause of this :/
