### ISSUE TITLE
Add a method to set page title for IE7

### ISSUE THREAD

**Issue by chuchuva** [cowboy/jquery-bbq#6]
This is not an issue, just a suggestion. If you use document.title to set page title your titles will not appear in history menu in Internet Explorer 7.

Repro steps:
1. Open [BBQ demo](http://chuchuva.com/demo/jquery-bbq/) in Internet Explorer 7
1. Click Next button few times
1. Open history menu

Observe: history menu contains full URLs
Expected: page titles (12, 13, 14 etc)

See http://chuchuva.com/pavel/2010/04/jquery-bbq-plugin-and-internet-explorer-7/

**Comment by chuchuva** [comment]
Something like this:

chuchuva/jquery-bbq@6efb3030b3dc843def62645f42d2ca4ed5b85eee

**Comment by cowboy** [comment]
This issue has been moved to [jQuery hashchange event](http://github.com/cowboy/jquery-hashchange/issues/issue/11).
