### ISSUE TITLE
Is the LICENSE "MIT & GPL" or "MIT OR GPL"?

### ISSUE THREAD

**Issue by gauntface** [cowboy/jquery-bbq#63]
Hi,

Just wanted to check what the license for this is. I'm always unsure when the statement is "dual licensed under MIT and GPL", which I interpret as both licenses applying instead of a selection the user can make, but wanted to check.

Thanks,
Matt

**Comment by jgonggrijp** [comment]
@cowboy I have this question, too. I want to republish just the `deparam` function on NPM; should I attach the MIT license, the GPL license, or both?

**Comment by cowboy** [comment]
You can choose either or both. It's up to you.

**Comment by jgonggrijp** [comment]
Thanks!
