### ISSUE TITLE
Android Browser (WebKit) hashchange event does not fire after zoom/resize

### ISSUE THREAD

**Issue by gaucho** [cowboy/jquery-bbq#7]
Got a brand new toy (HTC Desire) and went to try out my AJAX-heavy site that uses BBQ (great plugin btw - thank you!) - found my nav wasn't working after I resized (pinch/zoom) the page.  Figured it was mine but verified the problem also exists with this default example:

http://benalman.com/code/projects/jquery-bbq/examples/fragment-basic/

To reproduce - go to above page with HTC Desire (my version info below) and wait for it to load.  Click on the Chicken/Kababs link - it will work fine.  Now zoom out or in with multi-touch/pinch and try links again.  They no longer work.

Am I going crazy here?  Thanks very much in advance.

-Gaucho

Browser useragent reports version as: Mozilla/5.0 (Linux; U; Android 2.1-update1; en-gb; Desire_A8181 Build/ERE27) AppleWebKit/530.17 (KHTML, like Gecko) Version/4.0 Mobile Safari/530.17

**Comment by cowboy** [comment]
This is probably a mobile WebKit bug.. Does it also fail [on this test page](http://benalman.com/code/projects/jquery-hashchange/examples/bug-webkit-hash-iframe/child/)?

**Comment by gaucho** [comment]
That was quick :)

When the iframe is loaded - after hashtags are clicked, the back button does not go back through the history.  When not in iframe - it works as expected.

Both of these work the same for me whether it's initial load - or after a pinch/zoom - so I'm not sure it's related though.

Definitely happy to accept it's a Webkit bug and nothing to do with BBQ... just didn't know a better forum to ask this in to see if it had been raised before and if there's a workaround.

thanks again,

-Gaucho

**Comment by cowboy** [comment]
Well, there definitely is a known issue with Iframes and hash history in WebKit.. but I'm not aware of a bug with the hashchange event after a pinch+zoom. The best test I can think of is to set up a super-simple non-jQuery version that just polls the location.hash and outputs what the hash is when it's changed, and then test with that.

**Comment by gaucho** [comment]
I think I understand what you were after - please correct me if wrong.  I created the page at the bottom (I hope GitHub automatically quotes code!) and tried on my HTC Desire and no amount of pinching or zooming changed the hashtag before or after using the back button. 

<html>
<body>
<a href="javascript:alert(location.hash);"><h2>hash alert</h2><a>
<a href="#foo"><h2>go to foo</h2></a>
<a href="#bar"><h2>go to bar</h2></a>
<a name="foo">foo</a>
<a name="bar">bar</a>
</body>
</html>

**Comment by gaucho** [comment]
oops sorry - doesn't look like it automatically escapes html... here it is again escaped:

&lt;html&gt;
&lt;body&gt;
&lt;a href=&quot;javascript:alert(location.hash);&quot;&gt;&lt;h2&gt;hash alert&lt;/h2&gt;&lt;a&gt;
&lt;a href=&quot;#foo&quot;&gt;&lt;h2&gt;go to foo&lt;/h2&gt;&lt;/a&gt;
&lt;a href=&quot;#bar&quot;&gt;&lt;h2&gt;go to bar&lt;/h2&gt;&lt;/a&gt;
&lt;a name=&quot;foo&quot;&gt;foo&lt;/a&gt;
&lt;a name=&quot;bar&quot;&gt;bar&lt;/a&gt;
&lt;/body&gt;
&lt;/html&gt;

**Comment by cowboy** [comment]
Try this: http://jsbin.com/onayu3/6/

**Comment by gaucho** [comment]
tried it and before pinch/zoom, "polling" and "onhashchange" stay the same on each click and on reversing through history.

After pinch/zoom, polling no longer changes, but onhashchange continues to update forward and backward.

-Gaucho

**Comment by cowboy** [comment]
This bug seems to be related to [jQuery hashchange issue 7](http://github.com/cowboy/jquery-hashchange/issues#issue/7), so I'm closing it here. If you could, please add comments regarding the nature of your experience to the android bug tracker [Issue 8475](http://code.google.com/p/android/issues/detail?id=8475), since that seems to be the best place for it.
