### ISSUE TITLE
$.param.querystring removes [ ]  in the url

### ISSUE THREAD

**Issue by toamitkumar** [cowboy/jquery-bbq#8]
$.param.querystring("http://example.com?a[]=1&a[]=2&b=1", "b=2");, generates "http://example.com?a=1&a=2&b=2" instead of "http://example.com?a=[]1&a[]=2&b=2"

**Comment by cowboy** [comment]
From the [BBQ project page](http://benalman.com/projects/jquery-bbq-plugin/):

> Note: If you’re using jQuery 1.3.2 or earlier and need BBQ to merge query string or fragment params containing [], you’ll want to include the [jQuery 1.4 .param method](http://gist.github.com/206323) in your code.

Does that help?

**Comment by toamitkumar** [comment]
Sorry for the late response, this breaks.. I am on jQuery 1.3.2
Getting $.param.querystring is not a function

**Comment by cowboy** [comment]
Include the jQuery 1.4 param method _before_ including BBQ.

**Comment by toamitkumar** [comment]
Preferred to upgrade to jQuery 1.4.2 then putting the code you gave. It works !!
Thanks for your help...
